### ISSUE TITLE
SASyLF rename refactoring crashes when automatically run on Java Code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [boyland/sasylf#63]
```
!ENTRY org.eclipse.ltk.core.refactoring 4 10009 2014-08-29 20:59:47.461
!MESSAGE Participant 'org.sasylf.refactor.rename' removed due to the following 
exception
!STACK 1
org.eclipse.core.runtime.CoreException: No property tester contributes a 
property org.eclipse.core.resources.name to type class 
org.eclipse.jdt.internal.core.SourceType
    at org.eclipse.core.internal.expressions.TypeExtensionManager.getProperty(TypeExtensionManager.java:123)
    at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:96)
    at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
    at org.eclipse.core.internal.expressions.EnablementExpression.evaluate(EnablementExpression.java:53)
    at org.eclipse.ltk.internal.core.refactoring.ParticipantDescriptor.matches(ParticipantDescriptor.java:76)
    at org.eclipse.ltk.core.refactoring.participants.ParticipantExtensionPoint.getParticipants(ParticipantExtensionPoint.java:93)
    at org.eclipse.ltk.core.refactoring.participants.ParticipantManager.loadRenameParticipants(ParticipantManager.java:74)
    at org.eclipse.jdt.internal.corext.refactoring.rename.RenameModifications.loadParticipants(RenameModifications.java:193)
    at org.eclipse.jdt.internal.corext.refactoring.rename.JavaRenameProcessor.loadParticipants(JavaRenameProcessor.java:41)
    at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:233)
    at org.eclipse.ltk.core.refactoring.Refactoring.checkAllConditions(Refactoring.java:162)
    at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper$Operation.run(RefactoringExecutionHelper.java:80)
    at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
    at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:728)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2345)
    at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5331)
    at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:106)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
!SUBENTRY 1 org.eclipse.core.expressions 4 201 2014-08-29 20:59:47.462
!MESSAGE No property tester contributes a property 
org.eclipse.core.resources.name to type class 
org.eclipse.jdt.internal.core.SourceType

```

Original issue reported on code.google.com by `boyland....@gmail.com` on 30 Aug 2014 at 2:04

**Comment by boyland** [comment]
Bug still present in 1.4.0a2 for 'Move' Refactoring.
